"""
Report Generator
Builds the daily advisory report (HTML + Markdown) from the ranked focus list
and the crowd-intelligence debates, then stores it in the reports table.

Sections:
  1. Top Focus List   - ranked_focus_list for today's run.
  2. Today's Debates  - the 3 most actively contested stocks: high crowd
                        attention AND a sentiment_balance near zero (bull and
                        bear camps near parity). Bull case vs bear case are
                        shown side by side.

Usage:
    python pipeline/agents/report_generator.py [premarket|midday|close]
"""

import html as _html
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

from supabase import create_client

# ── Path setup ─────────────────────────────────────────────────────────────────
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import SUPABASE_SERVICE_KEY, SUPABASE_URL

# ── Settings ───────────────────────────────────────────────────────────────────
VALID_RUN_TYPES = ("premarket", "midday", "close")
FOCUS_LIMIT     = 15      # focus-list rows shown in the report
DEBATE_COUNT    = 3       # number of debates in "Today's Debates"
MIN_ATTENTION   = 30      # attention floor for a stock to count as "debated"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════════
# Data loaders
# ══════════════════════════════════════════════════════════════════════════════

def _load_focus(db, today: str, run_type: str) -> list[dict]:
    resp = (
        db.table("ranked_focus_list")
        .select("rank,ticker,composite_score,thesis")
        .eq("run_date", today)
        .eq("run_type", run_type)
        .order("rank")
        .limit(FOCUS_LIMIT)
        .execute()
    )
    return resp.data or []


def _load_debates(db, today: str, run_type: str) -> list[dict]:
    try:
        resp = (
            db.table("ticker_debates").select("*")
            .eq("snapshot_date", today).eq("run_type", run_type).execute()
        )
        return resp.data or []
    except Exception as exc:
        log.warning("ticker_debates query failed: %s", exc)
        return []


def _pick_debates(debates: list[dict]) -> list[dict]:
    """High attention AND sentiment_balance closest to zero = most contested."""
    eligible = [d for d in debates if float(d.get("attention_score") or 0) > MIN_ATTENTION]
    eligible.sort(key=lambda d: abs(float(d.get("sentiment_balance") or 0)))
    return eligible[:DEBATE_COUNT]


# ══════════════════════════════════════════════════════════════════════════════
# Markdown
# ══════════════════════════════════════════════════════════════════════════════

def _build_markdown(today, run_type, focus, debates) -> str:
    lines = [
        f"# Fortis Stock Intelligence -- {run_type.title()} Report",
        f"_{today}_",
        "",
        "## Top Focus List",
        "",
    ]
    if focus:
        lines += ["| Rank | Ticker | Score | Thesis |", "|---|---|---|---|"]
        for r in focus:
            thesis = (r.get("thesis") or "").replace("|", "\\|")
            lines.append(
                f"| {r['rank']} | {r['ticker']} | {r['composite_score']:.1f} | {thesis} |"
            )
    else:
        lines.append("_No ranked focus list available for this run._")

    lines += ["", "## Today's Debates", "",
              "The most actively contested stocks -- high crowd attention with "
              "bull and bear camps near parity.", ""]
    if debates:
        for d in debates:
            attn = float(d.get("attention_score") or 0)
            sb   = float(d.get("sentiment_balance") or 0)
            lines += [
                f"### {d['ticker']}  (attention {attn:.0f}/100, sentiment balance {sb:+.0f})",
                "",
                f"**Bull case:** {d.get('bull_case') or 'n/a'}",
                "",
                f"**Bear case:** {d.get('bear_case') or 'n/a'}",
                "",
                f"**Consensus tilt:** {d.get('consensus_tilt') or 'n/a'}",
                "",
                f"**Retail vs pro:** {d.get('retail_pro_divergence') or 'n/a'}",
                "",
            ]
    else:
        lines.append("_No debates cleared the attention threshold today._")

    lines += ["", "---", "_Generated by the Fortis pipeline. Not investment advice._"]
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# HTML
# ══════════════════════════════════════════════════════════════════════════════

def _esc(text) -> str:
    return _html.escape(str(text or ""))


def _build_html(today, run_type, focus, debates) -> str:
    parts = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'>",
        f"<title>Fortis Stock Intelligence - {_esc(run_type.title())} Report</title>",
        "<style>",
        "body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#1a1a1a;"
        "max-width:880px;margin:0 auto;padding:32px;line-height:1.5}",
        "h1{font-size:22px;margin-bottom:2px}h2{font-size:17px;margin-top:32px;"
        "border-bottom:2px solid #eee;padding-bottom:6px}",
        ".date{color:#888;font-size:13px}",
        "table{border-collapse:collapse;width:100%;font-size:13px;margin-top:8px}",
        "th,td{border:1px solid #e3e3e3;padding:6px 9px;text-align:left;vertical-align:top}",
        "th{background:#f6f6f6}",
        ".debate{display:flex;gap:14px;margin:14px 0}",
        ".bull,.bear{flex:1;padding:11px 13px;border-radius:7px;font-size:13px}",
        ".bull{background:#eafaf0;border:1px solid #b8e6c8}",
        ".bear{background:#fdeced;border:1px solid #f0bcc0}",
        ".bull h4{color:#1a7a3e;margin:0 0 5px}.bear h4{color:#b3262f;margin:0 0 5px}",
        ".dh{font-size:15px;font-weight:600;margin-top:18px}",
        ".meta{color:#888;font-size:12px;margin-bottom:2px}",
        ".extra{font-size:12px;color:#444;margin-top:6px}",
        ".foot{color:#999;font-size:11px;margin-top:34px}",
        "</style></head><body>",
        f"<h1>Fortis Stock Intelligence &mdash; {_esc(run_type.title())} Report</h1>",
        f"<div class='date'>{_esc(today)}</div>",
        "<h2>Top Focus List</h2>",
    ]

    if focus:
        parts.append("<table><tr><th>Rank</th><th>Ticker</th><th>Score</th>"
                      "<th>Thesis</th></tr>")
        for r in focus:
            parts.append(
                f"<tr><td>{r['rank']}</td><td><b>{_esc(r['ticker'])}</b></td>"
                f"<td>{r['composite_score']:.1f}</td><td>{_esc(r.get('thesis'))}</td></tr>"
            )
        parts.append("</table>")
    else:
        parts.append("<p><em>No ranked focus list available for this run.</em></p>")

    parts.append("<h2>Today's Debates</h2>")
    parts.append("<p class='meta'>The most actively contested stocks &mdash; high "
                 "crowd attention with bull and bear camps near parity.</p>")

    if debates:
        for d in debates:
            attn = float(d.get("attention_score") or 0)
            sb   = float(d.get("sentiment_balance") or 0)
            parts.append(
                f"<div class='dh'>{_esc(d['ticker'])}</div>"
                f"<div class='meta'>attention {attn:.0f}/100 &middot; "
                f"sentiment balance {sb:+.0f}</div>"
                "<div class='debate'>"
                f"<div class='bull'><h4>Bull case</h4>{_esc(d.get('bull_case'))}</div>"
                f"<div class='bear'><h4>Bear case</h4>{_esc(d.get('bear_case'))}</div>"
                "</div>"
                f"<div class='extra'><b>Consensus tilt:</b> {_esc(d.get('consensus_tilt'))}<br>"
                f"<b>Retail vs pro:</b> {_esc(d.get('retail_pro_divergence'))}</div>"
            )
    else:
        parts.append("<p><em>No debates cleared the attention threshold today.</em></p>")

    parts.append("<div class='foot'>Generated by the Fortis pipeline. "
                 "Not investment advice.</div>")
    parts.append("</body></html>")
    return "".join(parts)


# ══════════════════════════════════════════════════════════════════════════════
# Entry point
# ══════════════════════════════════════════════════════════════════════════════

def run(run_type: str = "midday") -> None:
    if run_type not in VALID_RUN_TYPES:
        log.warning("Unknown run_type '%s' -- defaulting to 'midday'", run_type)
        run_type = "midday"

    today = datetime.now(timezone.utc).date().isoformat()
    db = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

    focus = _load_focus(db, today, run_type)
    log.info("Loaded %d focus-list rows for %s/%s", len(focus), today, run_type)
    if not focus:
        log.warning("No ranked_focus_list rows -- run ranking_engine.py first.")

    all_debates = _load_debates(db, today, run_type)
    debates = _pick_debates(all_debates)
    log.info("Selected %d debates (of %d) for Today's Debates section",
             len(debates), len(all_debates))

    markdown = _build_markdown(today, run_type, focus, debates)
    html_doc = _build_html(today, run_type, focus, debates)

    row = {
        "report_type":      run_type,
        "report_date":      today,
        "content_html":     html_doc,
        "content_markdown": markdown,
        "delivered_email":  False,
    }
    try:
        resp = db.table("reports").insert(row).execute()
        rid = resp.data[0]["id"] if resp.data else "?"
        log.info("Report stored in reports table (id=%s)", rid)
    except Exception as exc:
        log.error("reports insert failed: %s", exc)

    log.info("")
    log.info("== Report preview (markdown) ==")
    for line in markdown.splitlines():
        log.info(line)


if __name__ == "__main__":
    arg = sys.argv[1].lower() if len(sys.argv) > 1 else "midday"
    run(arg)
