// TEMPLATE — must be reviewed by a qualified professional before production use.
//
// Research-not-advice disclaimer for Christopher Edwards Financial Associates. Expands the platform's existing
// fiduciary language ("For licensed advisor review — not investment advice")
// into a fuller statement. Not legal advice; have counsel review.

export const metadata = { title: "Disclaimer · Christopher Edwards Financial Associates" }

const EFFECTIVE_DATE = "June 11, 2026"

export default function DisclaimerPage() {
  return (
    <div className="report-prose">
      <p className="text-eyebrow">Legal</p>
      <h1 className="mt-2 text-h1">Disclaimer</h1>
      <p className="mt-3 text-small text-muted-foreground">
        Effective {EFFECTIVE_DATE}
      </p>

      <p className="mt-8">
        <strong>For licensed advisor review, not investment advice.</strong>{" "}
        Christopher Edwards Financial Associates (the &ldquo;Service&rdquo;) is a research and
        analytics tool provided by Christopher Edwards Financial Associates for informational and
        educational purposes only.
      </p>

      <h2>No investment advice</h2>
      <p>
        Nothing in the Service constitutes investment, financial, legal,
        accounting, or tax advice, and nothing in it should be construed as a
        recommendation, offer, or solicitation to buy, sell, or hold any
        security or to adopt any investment strategy. The Service does not
        account for your specific objectives, financial situation, or needs.
      </p>

      <h2>No fiduciary or advisory relationship</h2>
      <p>
        Use of the Service does not create an advisor-client, fiduciary, or
        similar relationship between you and Christopher Edwards Financial Associates. Outputs are
        intended to be reviewed by a licensed investment professional who
        exercises independent judgment before any action is taken.
      </p>

      <h2>Delayed and third-party data</h2>
      <p>
        Prices, fundamentals, and other figures are sourced from third parties
        and are delayed (typically by at least 15 minutes). They may be
        inaccurate, incomplete, or out of date. The Service is provided
        &ldquo;as is&rdquo; without warranty of any kind.
      </p>

      <h2>Automated and AI-generated content</h2>
      <p>
        Portions of the Service are generated by automated scoring models and
        large language models. Such content may contain errors, omissions, or
        misclassifications, and should be independently verified against
        primary sources before being relied upon.
      </p>

      <h2>No guarantee of performance</h2>
      <p>
        Past performance, back-tested results, and any track-record figures are
        not indicative of future results. Conviction grades and scores are
        opinions, not guarantees. Investing involves risk, including the
        possible loss of principal.
      </p>

      <h2>Your responsibility</h2>
      <p>
        You are solely responsible for evaluating the merits and risks of any
        investment decision. Conduct your own due diligence and consult a
        qualified, licensed professional before acting on any information from
        the Service. To the maximum extent permitted by law, Christopher Edwards Financial Associates
        accepts no liability for any loss arising from use of the Service.
      </p>
    </div>
  )
}
