-- ============================================================
-- 030_backtest_picks.sql
-- Hypothetical picks generated by pipeline/agents/backtest_engine.py's
-- historical_backtest() -- one row per (backtest_date, run_type, ticker).
--
-- Separate from ranked_focus_list so live picks and reconstructed picks
-- never get confused in any downstream query.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.backtest_picks (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  backtest_date   date    NOT NULL,
  run_type        text    NOT NULL,           -- premarket | midday | close
  rank            int     NOT NULL,
  ticker          text    NOT NULL,
  composite_score numeric NOT NULL,
  weights_label   text,                       -- 'baseline' or e.g. 'news_-10pct'
  created_at      timestamptz DEFAULT now(),
  UNIQUE (backtest_date, run_type, ticker)
);

CREATE INDEX IF NOT EXISTS idx_backtest_picks_date
  ON public.backtest_picks (backtest_date DESC, rank);

ALTER TABLE public.backtest_picks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_read" ON public.backtest_picks
  FOR SELECT TO authenticated USING (true);

COMMENT ON TABLE public.backtest_picks IS
  'Hypothetical picks the system WOULD have produced on backtest_date using '
  'only data available on or before that date (lookahead-safe via '
  'AsOfSignalStore in backtest_engine.py). Never mix with ranked_focus_list.';
